version: "2"
services:
  template:
    build:
      context: ./
      dockerfile: dev.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www

  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - template
    ports:
      - 8889:80

